#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from pathlib import Path

import joblib
import numpy as np
from sklearn.pipeline import Pipeline


OUTPUT_FIELDS = [
    "sample_id",
    "split",
    "source_page_id",
    "source_region_id",
    "page_no",
    "bbox",
    "text",
    "gold_label",
    "predicted_label",
    "confidence",
    "threshold",
    "hint_label",
    "hint_action",
    "hint_status",
    "reason",
]

META_COLUMNS = {
    "sample_id",
    "source_dataset",
    "source_page_id",
    "source_region_id",
    "page_no",
    "feature_set",
    "source_label",
    "target_label",
    "split",
    "text",
    "notes",
}


class HintExportError(RuntimeError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export fail-closed distilled hints from an offline HGB teacher."
    )
    parser.add_argument("--features", required=True, help="Feature TSV path.")
    parser.add_argument(
        "--model",
        required=True,
        help="Teacher model path. Used when predictions are not precomputed.",
    )
    parser.add_argument(
        "--predictions",
        help="Optional predictions TSV generated by train_doclaynet_baseline.py. Reused when present.",
    )
    parser.add_argument(
        "--adapter-rows",
        help="Optional adapter task_a_rows.tsv for bbox backfill. Inferred from --features when omitted.",
    )
    parser.add_argument("--output", required=True, help="Output TSV path.")
    parser.add_argument(
        "--thresholds",
        required=True,
        help="Comma-separated confidence thresholds, e.g. 0.90,0.95",
    )
    parser.add_argument(
        "--allowed-labels",
        required=True,
        help="Comma-separated labels allowed to emit as hints.",
    )
    parser.add_argument(
        "--deny-labels",
        default="caption",
        help="Comma-separated labels that must never emit as hints.",
    )
    parser.add_argument(
        "--split",
        default="heldout",
        help="Split to export, usually heldout or dev.",
    )
    return parser.parse_args()


def read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise HintExportError(f"missing TSV: {path}")
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def write_tsv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)


def parse_list(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def parse_thresholds(raw: str) -> list[float]:
    out = []
    for item in parse_list(raw):
        try:
            value = float(item)
        except ValueError as exc:
            raise HintExportError(f"invalid threshold: {item!r}") from exc
        out.append(value)
    if not out:
        raise HintExportError("no thresholds provided")
    return out


def feature_lookup(rows: list[dict[str, str]], split: str) -> dict[str, dict[str, str]]:
    return {
        row["sample_id"]: row
        for row in rows
        if row.get("split") == split
    }


def feature_columns(rows: list[dict[str, str]]) -> list[str]:
    if not rows:
        return []
    return [name for name in rows[0].keys() if name not in META_COLUMNS]


def rows_to_matrix(rows: list[dict[str, str]], columns: list[str]) -> np.ndarray:
    return np.array(
        [[float(row[column]) for column in columns] for row in rows],
        dtype=np.float64,
    )


def model_classes(model: object) -> list[str]:
    classes = getattr(model, "classes_", None)
    if classes is not None:
        return list(classes)
    if isinstance(model, Pipeline):
        clf = model.named_steps.get("clf")
        if clf is not None and hasattr(clf, "classes_"):
            return list(clf.classes_)
    raise HintExportError("model does not expose classes_")


def infer_adapter_rows_path(features_path: Path) -> Path | None:
    try:
        local_only_root = features_path.parents[4]
        dataset_name = features_path.parents[2].name
        subset_name = features_path.parents[1].name
    except IndexError:
        return None
    candidate = local_only_root / "adapter_outputs" / dataset_name / subset_name / "task_a_rows.tsv"
    return candidate if candidate.is_file() else None


def adapter_bbox_lookup(path: Path | None) -> dict[str, str]:
    if path is None or not path.is_file():
        return {}
    rows = read_tsv(path)
    return {row["sample_id"]: row.get("bbox", "") for row in rows}


def build_prediction_rows_from_model(
    *,
    model_path: Path,
    feature_rows: list[dict[str, str]],
    split: str,
) -> list[dict[str, str]]:
    model = joblib.load(model_path)
    split_rows = [row for row in feature_rows if row.get("split") == split]
    if not split_rows:
        raise HintExportError(f"no feature rows found for split={split}")
    columns = feature_columns(feature_rows)
    if not columns:
        raise HintExportError("feature TSV does not expose training columns")
    x = rows_to_matrix(split_rows, columns)
    predicted = list(model.predict(x))
    probabilities = model.predict_proba(x)
    probability_by_label = {label: index for index, label in enumerate(model_classes(model))}

    rows: list[dict[str, str]] = []
    for feature_row, pred, probs in zip(split_rows, predicted, probabilities):
        confidence = probs[probability_by_label[pred]]
        rows.append(
            {
                "split": feature_row["split"],
                "sample_id": feature_row["sample_id"],
                "source_page_id": feature_row["source_page_id"],
                "source_region_id": feature_row["source_region_id"],
                "gold_label": feature_row["target_label"],
                "predicted_label": pred,
                "text_missing": feature_row.get("text_missing", ""),
                "confidence": f"{confidence:.6f}",
                "text": feature_row.get("text", ""),
                "notes": feature_row.get("notes", ""),
            }
        )
    return rows


def build_hint_row(
    *,
    feature_row: dict[str, str],
    prediction_row: dict[str, str],
    bbox_lookup: dict[str, str],
    threshold: float,
    allowed_labels: set[str],
    deny_labels: set[str],
) -> dict[str, str]:
    predicted = prediction_row["predicted_label"]
    gold = prediction_row["gold_label"]
    try:
        confidence = float(prediction_row["confidence"])
    except ValueError as exc:
        raise HintExportError(
            f"invalid confidence for sample {prediction_row['sample_id']}: {prediction_row['confidence']!r}"
        ) from exc

    hint_action = "no_override"
    hint_status = "below_threshold"
    hint_label = ""
    reason = f"confidence<{threshold:.2f}"

    if predicted in deny_labels:
        hint_status = "deny_label"
        reason = f"deny_label:{predicted}"
    elif confidence < threshold:
        hint_status = "below_threshold"
        reason = f"confidence<{threshold:.2f}"
    elif predicted not in allowed_labels:
        hint_status = "deny_label"
        reason = f"not_allowed:{predicted}"
    else:
        hint_action = "suggest_block_label"
        hint_label = predicted
        if predicted == gold:
            hint_status = "emit"
            reason = f"confidence>={threshold:.2f}"
        else:
            hint_status = "wrong_prediction"
            reason = f"predicted:{predicted};gold:{gold}"

    return {
        "sample_id": prediction_row["sample_id"],
        "split": prediction_row["split"],
        "source_page_id": prediction_row["source_page_id"],
        "source_region_id": prediction_row["source_region_id"],
        "page_no": feature_row.get("page_no", ""),
        "bbox": bbox_lookup.get(prediction_row["sample_id"], feature_row.get("bbox", "")),
        "text": prediction_row.get("text", ""),
        "gold_label": gold,
        "predicted_label": predicted,
        "confidence": f"{confidence:.6f}",
        "threshold": f"{threshold:.2f}",
        "hint_label": hint_label,
        "hint_action": hint_action,
        "hint_status": hint_status,
        "reason": reason,
    }


def main() -> int:
    args = parse_args()
    thresholds = parse_thresholds(args.thresholds)
    allowed_labels = set(parse_list(args.allowed_labels))
    deny_labels = set(parse_list(args.deny_labels))
    if not allowed_labels:
        raise HintExportError("allowed-labels must not be empty")

    features_path = Path(args.features)
    feature_rows = read_tsv(features_path)
    predictions_path = Path(args.predictions) if args.predictions else None
    model_path = Path(args.model)
    if predictions_path is not None and predictions_path.is_file():
        prediction_rows = read_tsv(predictions_path)
    else:
        prediction_rows = build_prediction_rows_from_model(
            model_path=model_path,
            feature_rows=feature_rows,
            split=args.split,
        )
    adapter_rows_path = (
        Path(args.adapter_rows)
        if args.adapter_rows
        else infer_adapter_rows_path(features_path)
    )
    bbox_lookup = adapter_bbox_lookup(adapter_rows_path)

    feature_by_sample = feature_lookup(feature_rows, args.split)
    rows: list[dict[str, str]] = []
    missing_count = 0

    for prediction_row in prediction_rows:
        if prediction_row.get("split") != args.split:
            continue
        sample_id = prediction_row["sample_id"]
        feature_row = feature_by_sample.get(sample_id)
        if feature_row is None:
            missing_count += 1
            for threshold in thresholds:
                rows.append(
                    {
                        "sample_id": sample_id,
                        "split": prediction_row.get("split", ""),
                        "source_page_id": prediction_row.get("source_page_id", ""),
                        "source_region_id": prediction_row.get("source_region_id", ""),
                        "page_no": "",
                        "bbox": bbox_lookup.get(sample_id, ""),
                        "text": prediction_row.get("text", ""),
                        "gold_label": prediction_row.get("gold_label", ""),
                        "predicted_label": prediction_row.get("predicted_label", ""),
                        "confidence": prediction_row.get("confidence", ""),
                        "threshold": f"{threshold:.2f}",
                        "hint_label": "",
                        "hint_action": "no_override",
                        "hint_status": "missing_proba",
                        "reason": "missing_feature_row",
                    }
                )
            continue
        for threshold in thresholds:
            rows.append(
                build_hint_row(
                    feature_row=feature_row,
                    prediction_row=prediction_row,
                    bbox_lookup=bbox_lookup,
                    threshold=threshold,
                    allowed_labels=allowed_labels,
                    deny_labels=deny_labels,
                )
            )

    if not rows:
        raise HintExportError(f"no rows exported for split={args.split}")

    write_tsv(Path(args.output), rows)
    status_counts = Counter(row["hint_status"] for row in rows)
    emit_counts = Counter(row["hint_label"] for row in rows if row["hint_status"] == "emit")
    print(
        f"distilled hints export complete: split={args.split} rows={len(rows)} "
        f"status_counts={dict(sorted(status_counts.items()))} "
        f"emit_label_counts={dict(sorted(emit_counts.items()))} "
        f"missing_feature_rows={missing_count}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
