#!/usr/bin/env python3
"""
Generate compact CP936/GBK double-byte lookup blobs for the vendored PDF text
packages.

Source mapping:
  https://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP936.TXT

License:
  Unicode Data Files are covered by the Unicode License v3.
  See: https://www.unicode.org/copyright.html

Generation method:
  - Keep only double-byte CP936 entries whose lead byte is 0x81..0xFE and
    whose trail byte is in 0x40..0x7E or 0x80..0xFE.
  - Convert each valid lead/trail pair into a GBK pointer index:
      (lead - 0x81) * 190 + trail_offset
  - Emit a fixed-size pointer table with 23940 slots.
  - Store the table as a compact hex blob where each slot is:
      4 hex digits for a BMP codepoint, or 0000 when unmapped.
  - Runtime lookup decodes the codepoint directly from the blob, avoiding a
    large static pair array or Map initializer.
"""

from __future__ import annotations

import argparse
import pathlib
import urllib.request


SOURCE_URL = "https://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP936.TXT"
SLOT_COUNT = 0xFE - 0x81 + 1
TRAILS_PER_LEAD = (0x7E - 0x40 + 1) + (0xFE - 0x80 + 1)
POINTER_COUNT = SLOT_COUNT * TRAILS_PER_LEAD


def gbk_trail_offset(trail: int) -> int | None:
    if 0x40 <= trail <= 0x7E:
        return trail - 0x40
    if 0x80 <= trail <= 0xFE:
        return 63 + (trail - 0x80)
    return None


def gbk_pointer(code: int) -> int | None:
    if code <= 0xFF:
        return None
    lead = code >> 8
    trail = code & 0xFF
    if not (0x81 <= lead <= 0xFE):
        return None
    trail_offset = gbk_trail_offset(trail)
    if trail_offset is None:
        return None
    return (lead - 0x81) * TRAILS_PER_LEAD + trail_offset


def load_mapping_text(path_or_url: str) -> str:
    if path_or_url.startswith("http://") or path_or_url.startswith("https://"):
        with urllib.request.urlopen(path_or_url) as response:
            return response.read().decode("ascii")
    return pathlib.Path(path_or_url).read_text(encoding="ascii")


def build_blob(mapping_text: str) -> str:
    table: list[int] = [0] * POINTER_COUNT
    for raw_line in mapping_text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) < 2:
            continue
        left = fields[0].strip()
        right = fields[1].strip()
        if not left.startswith("0x") or not right.startswith("0x"):
            continue
        code = int(left, 16)
        codepoint = int(right, 16)
        pointer = gbk_pointer(code)
        if pointer is None:
            continue
        if codepoint > 0xFFFF:
            raise SystemExit(
                f"Encountered non-BMP codepoint U+{codepoint:04X} for CP936 code 0x{code:04X}"
            )
        table[pointer] = codepoint
    return "".join(f"{value:04x}" for value in table)


def moon_string_literal(blob: str, chunk_size: int) -> str:
    chunks = [blob[i : i + chunk_size] for i in range(0, len(blob), chunk_size)]
    if len(chunks) == 1:
        return f'let gbk_blob : String = "{chunks[0]}"'
    lines = [f'let gbk_blob : String = "{chunks[0]}" +']
    for chunk in chunks[1:-1]:
        lines.append(f'  "{chunk}" +')
    lines.append(f'  "{chunks[-1]}"')
    return "\n".join(lines)


TEMPLATE = """///|
/// Compact CP936/GBK double-byte mapping for no-/ToUnicode simple-font fallback.
///
/// Generated by `tools/pdf_encoding/generate_cp936_blob.py` from:
///   {source_url}
///
/// License:
///   Unicode Data Files are covered by the Unicode License v3.
///   See: https://www.unicode.org/copyright.html
///
/// Generation method:
/// - keep only double-byte CP936 entries (0x81..0xFE lead bytes)
/// - index by GBK pointer: (lead - 0x81) * 190 + trail_offset
/// - store each pointer slot as 4 hex digits for a BMP codepoint
/// - use `0000` for unmapped slots
/// - decode on demand without a large static pair array or Map initializer

///|
{blob_literal}

///|
fn gbk_hex_digit_value(ch : Char) -> Int {{
  if ch >= '0' && ch <= '9' {{
    ch.to_int() - '0'.to_int()
  }} else if ch >= 'a' && ch <= 'f' {{
    ch.to_int() - 'a'.to_int() + 10
  }} else if ch >= 'A' && ch <= 'F' {{
    ch.to_int() - 'A'.to_int() + 10
  }} else {{
    0
  }}
}}

///|
fn gbk_hex_u16(chars : Array[Char], start : Int) -> Int {{
  (gbk_hex_digit_value(chars[start]) << 12) |
  (gbk_hex_digit_value(chars[start + 1]) << 8) |
  (gbk_hex_digit_value(chars[start + 2]) << 4) |
  gbk_hex_digit_value(chars[start + 3])
}}

///|
let gbk_blob_chars : Array[Char] = gbk_blob.to_array()

///|
fn gbk_trail_offset(byte : Int) -> Int? {{
  if byte >= 0x40 && byte <= 0x7e {{
    Some(byte - 0x40)
  }} else if byte >= 0x80 && byte <= 0xfe {{
    Some(63 + (byte - 0x80))
  }} else {{
    None
  }}
}}

///|
fn gbk_pointer_of_pair(lead : Int, trail : Int) -> Int? {{
  if lead < 0x81 || lead > 0xfe {{
    return None
  }}
  match gbk_trail_offset(trail) {{
    Some(offset) => Some((lead - 0x81) * 190 + offset)
    None => None
  }}
}}

///|
fn gbk_codepoint_at_pointer(pointer : Int) -> Int? {{
  let start = pointer * 4
  if start + 3 >= gbk_blob_chars.length() {{
    return None
  }}
  let codepoint = gbk_hex_u16(gbk_blob_chars, start)
  if codepoint == 0 {{
    None
  }} else {{
    Some(codepoint)
  }}
}}

///|
pub fn PdfTextUtil::codepoints_of_gbk(
  _self : PdfTextUtil,
  bytes : Array[Int],
) -> Array[Int]? {{
  let out = Array::new()
  let mut i = 0
  while i < bytes.length() {{
    let b = bytes[i]
    if b <= 0x7f {{
      out.push(b)
      i = i + 1
      continue
    }}
    if i + 1 >= bytes.length() {{
      return None
    }}
    let lead = b
    let trail = bytes[i + 1]
    let pointer = match gbk_pointer_of_pair(lead, trail) {{
      Some(pointer) => pointer
      None => return None
    }}
    let codepoint = match gbk_codepoint_at_pointer(pointer) {{
      Some(codepoint) => codepoint
      None => return None
    }}
    out.push(codepoint)
    i = i + 2
  }}
  Some(out)
}}
"""


def write_output(path: pathlib.Path, source_url: str, blob: str, chunk_size: int) -> None:
    content = TEMPLATE.format(
        source_url=source_url,
        blob_literal=moon_string_literal(blob, chunk_size),
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mapping", default=SOURCE_URL)
    parser.add_argument("--chunk-size", type=int, default=256)
    parser.add_argument("outputs", nargs="+")
    args = parser.parse_args()

    mapping_text = load_mapping_text(args.mapping)
    blob = build_blob(mapping_text)
    for output in args.outputs:
        write_output(pathlib.Path(output), args.mapping, blob, args.chunk_size)


if __name__ == "__main__":
    main()
